[build]
builder = "railpack"
buildCommand = "bun install && bun run db:generate && bun run build"

[deploy]
preDeployCommand = ["bun run db:deploy"]
startCommand = "node dist/server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
